version: "3"
services:
  php:
    build: "./"
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ${WORK_DIR}:/var/www/html
      - ${VIRTUALHOST_CONF}:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${SQL_DATA_VOLUME}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - my-network

  composer:
    image: composer:latest
    volumes:
      - ${WORK_DIR}:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    command: ["sh", "-c", "composer install && tail -f /dev/null"]
    networks:
      - my-network

networks:
  my-network:
