#!/usr/bin/php
<?php
require __DIR__ . '/vendor/autoload.php';
require_once './src/helpers/jcli.php';

use splitbrain\phpcli\CLI;
use splitbrain\phpcli\Options;

class Jam extends CLI
{
    /**
     * register options and arguments
     *
     * @param Options $options
     * 
     * @return void
     */
    protected function setup(Options $options)
    {
        $options->setHelp('Welcome To JAM CLI Powered By Brainsplit/php-cli');

        $files = array_diff(scandir(getcwd() . '/applications/cli'), array('', '.', '..'));

        $cliClasses = [];
        foreach ($files as $file) {
            $cliClasses[] = explode('.', $file)[0];
        }

        foreach ($cliClasses as $class) {
            jCli::factory($class)
                ->setCliOption($options)
                ->setup();
        }
    }

    /**
     * implement main code
     *
     * @param Options $options
     * 
     * @return void
     */
    protected function main(Options $options)
    {
        if (count($_SERVER['argv']) == 1) {
            echo $options->help();
            return;
        }

        $cmd = $options->getCmd();

        try {
            if ($cmd === '') {
                throw new Exception("No command class found for your command. "
                    . "Please make sure the class name of your command strictly matches with the file name.");
            }
            if (!jCli::factory($cmd)->setCliObject($this)->perform($options->getOpt(), $options->getArgs())) {
                echo $options->help();
                return;
            }
        } catch (Exception $e) {
            $this->error($e->getMessage());
        }
    }
}

$cli = new Jam();
$cli->run();
